PKGNAME := ctest
CTEST_HEADERS := $(PKGINC_H) $(CBASE_HEADERS)
CTEST_INCLUDES := $(PKGINCDIR) $(CBASE_INCLUDES)

CTEST_SRC := $(PKGSRCDIR)
CTEST_H := $(PKGSRC_H)
CTEST_INTDIR := $(INTSRCDIR)
CTEST_OBJ := $(PKGSRC_OBJ)
CTEST_GCDA := $(PKGSRC_GCDA)
CTEST := $(PKGLIB)

.PHONY: ctest
ctest: $(CTEST)

$(CTEST): $(CTEST_OBJ)
	@mkdir -p $(@D)
	ar rcs $@ $(CTEST_OBJ)

$(CTEST_INTDIR)%.o: $(CTEST_SRC)%.c $(CTEST_H) $(CTEST_HEADERS)
	@mkdir -p $(@D)
	$(TCC) -m$(BITS) -c $(patsubst %,-I%,$(CTEST_SRC) $(CTEST_INCLUDES)) $(CFLAGS) -o $@ $<

CTEST_TEST_LIBS := $(CTEST) $(CBASE)

CTEST_TEST_SRC := $(PKGTESTDIR)
CTEST_TEST_H := $(PKGTEST_H)
CTEST_TEST_INTDIR := $(INTTESTDIR)
CTEST_TEST_OBJ := $(PKGTEST_OBJ)
CTEST_TEST_GCDA := $(PKGTEST_GCDA)
CTEST_TEST := $(PKGTEST)

.PHONY: ctest_test
ctest_test: $(CTEST_TEST)
	@rm -rf $(CTEST_GCDA) $(CTEST_TEST_GCDA)
	$(CTEST_TEST)

$(CTEST_TEST): $(CTEST_TEST_OBJ) $(CTEST_TEST_LIBS)
	@mkdir -p $(@D)
	$(TCC) -m$(BITS) $(LDFLAGS) -o $@ $(CTEST_TEST_OBJ) -L$(LIBSDIR) $(patsubst %,-l:%,$(notdir $(CTEST_TEST_LIBS)))

$(CTEST_TEST_INTDIR)%.o: $(CTEST_TEST_SRC)%.c $(CTEST_TEST_H) $(CTEST_HEADERS)
	@mkdir -p $(@D)
	$(TCC) -m$(BITS) -c $(patsubst %,-I%,$(CTEST_TEST_SRC) $(CTEST_INCLUDES)) $(CFLAGS) -o $@ $<
